import { IsString, IsOptional, IsEnum, IsObject } from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

/**
 * Entity types that can be generated by AI Builder
 */
export enum AIBuilderEntityType {
  WEB_FORM = 'web-form',
  CUSTOM_FIELDS = 'custom-fields',
  EMAIL_TEMPLATE = 'email-template',
  ASSIGNMENT_RULE = 'assignment-rule',
  WORKFLOW = 'workflow',
  PRODUCT = 'product',
  PROFILE = 'profile',
  REPORT = 'report',
  SMART_BUILDER = 'smart-builder',
  TERRITORY = 'territory',
  PLAYBOOK = 'playbook',
}

/**
 * Context for AI generation - helps AI understand existing setup
 */
export class GenerationContextDto {
  @ApiPropertyOptional({ description: 'Existing field names to avoid duplicates' })
  @IsOptional()
  existingFields?: string[];

  @ApiPropertyOptional({ description: 'Industry context (e.g., "SaaS", "Real Estate", "Healthcare")' })
  @IsOptional()
  @IsString()
  industry?: string;

  @ApiPropertyOptional({ description: 'Company type (e.g., "B2B", "B2C", "Enterprise")' })
  @IsOptional()
  @IsString()
  companyType?: string;

  @ApiPropertyOptional({ description: 'Target entity for custom fields (LEAD, CONTACT, ACCOUNT, OPPORTUNITY)' })
  @IsOptional()
  @IsString()
  targetEntity?: string;

  @ApiPropertyOptional({ description: 'Available team members for assignment rules' })
  @IsOptional()
  teamMembers?: Array<{ id: string; name: string; email: string }>;

  @ApiPropertyOptional({ description: 'Available merge fields for email templates' })
  @IsOptional()
  mergeFields?: string[];

  @ApiPropertyOptional({ description: 'Previous conversation for refinement' })
  @IsOptional()
  previousMessages?: Array<{ role: 'user' | 'assistant'; content: string }>;
}

/**
 * Request DTO for AI Builder generation
 */
export class GenerateConfigDto {
  @ApiProperty({
    description: 'Type of entity to generate',
    enum: AIBuilderEntityType,
  })
  @IsEnum(AIBuilderEntityType)
  entityType: AIBuilderEntityType;

  @ApiProperty({
    description: 'Natural language description of what to create',
    example: 'Create a contact form for enterprise software leads that captures their name, work email, company, job title, company size, and what challenges they\'re facing',
  })
  @IsString()
  prompt: string;

  @ApiPropertyOptional({
    description: 'Additional context for generation',
    type: GenerationContextDto,
  })
  @IsOptional()
  @IsObject()
  context?: GenerationContextDto;
}

/**
 * Generated entity in the preview
 */
export class GeneratedEntityDto {
  @ApiProperty({ description: 'Type of generated entity' })
  entityType: string;

  @ApiProperty({ description: 'Brief description of what was generated' })
  description: string;

  @ApiProperty({ description: 'Number of items generated (e.g., fields, conditions)' })
  count?: number;
}

/**
 * Preview of what will be created
 */
export class GenerationPreviewDto {
  @ApiProperty({ description: 'Human-readable summary of what will be created' })
  summary: string;

  @ApiProperty({ description: 'List of entities that will be generated', type: [GeneratedEntityDto] })
  entities: GeneratedEntityDto[];

  @ApiPropertyOptional({ description: 'Warnings about the generation' })
  warnings?: string[];

  @ApiPropertyOptional({ description: 'Suggestions for improvements' })
  suggestions?: string[];
}

/**
 * Response DTO for AI Builder generation
 */
export class GenerateConfigResponseDto {
  @ApiProperty({ description: 'Whether generation was successful' })
  success: boolean;

  @ApiPropertyOptional({ description: 'Preview of what will be created' })
  preview?: GenerationPreviewDto;

  @ApiPropertyOptional({ description: 'Raw configuration object matching the entity DTO' })
  rawConfig?: Record<string, any>;

  @ApiPropertyOptional({ description: 'Error message if generation failed' })
  error?: string;

  @ApiPropertyOptional({ description: 'Conversation ID for follow-up refinements' })
  conversationId?: string;
}

/**
 * Request DTO for refining a previous generation
 */
export class RefineConfigDto {
  @ApiProperty({ description: 'The refinement instruction' })
  @IsString()
  prompt: string;

  @ApiProperty({ description: 'Previous raw config to refine' })
  @IsObject()
  previousConfig: Record<string, any>;

  @ApiProperty({ description: 'Entity type', enum: AIBuilderEntityType })
  @IsEnum(AIBuilderEntityType)
  entityType: AIBuilderEntityType;

  @ApiPropertyOptional({ description: 'Conversation ID from previous generation' })
  @IsOptional()
  @IsString()
  conversationId?: string;
}
