module.exports = {
  apps: [
    {
      name: 'salesos-backend',
      cwd: '../api',
      script: 'dist/src/main.js',
      node_args: '--enable-source-maps',
      env: {
        NODE_ENV: 'production',
      },
      watch: false,
      instances: 2,
      exec_mode: 'cluster',
      autorestart: true,
      max_memory_restart: '768M',
      error_file: '../logs/backend-error.log',
      out_file: '../logs/backend-out.log',
      log_file: '../logs/backend-combined.log',
      time: true,
      listen_timeout: 30000,
    },
    {
      name: 'salesos-frontend',
      cwd: '../',
      script: 'node_modules/.bin/serve',
      args: '-s dist -l 5001',
      env: {
        NODE_ENV: 'production',
      },
      watch: false,
      instances: 1,
      autorestart: true,
      max_memory_restart: '200M',
      error_file: '../logs/frontend-error.log',
      out_file: '../logs/frontend-out.log',
      log_file: '../logs/frontend-combined.log',
      time: true,
    },
    {
      name: 'salesos-docs',
      cwd: '../docs/.next/standalone',
      script: 'server.js',
      env: {
        NODE_ENV: 'production',
        PORT: 5002,
        HOSTNAME: '0.0.0.0',
      },
      watch: false,
      instances: 1,
      autorestart: true,
      max_memory_restart: '300M',
      error_file: '../logs/docs-error.log',
      out_file: '../logs/docs-out.log',
      log_file: '../logs/docs-combined.log',
      time: true,
    },
  ],
};
