import { CRMTemplate } from './types';

/**
 * HubSpot CRM Template
 *
 * Field mappings for migrating from HubSpot to SalesOS.
 * HubSpot uses different field naming conventions than Salesforce.
 */
export const hubspotTemplate: CRMTemplate = {
  name: 'HubSpot',
  code: 'hubspot',
  exportFields: {
    leads: [
      {
        crmField: 'First Name',
        salesosField: 'firstName',
        aliases: ['firstname', 'First_Name', 'fname'],
        required: true,
        description: 'Lead first name',
      },
      {
        crmField: 'Last Name',
        salesosField: 'lastName',
        aliases: ['lastname', 'Last_Name', 'lname', 'Surname'],
        required: true,
        description: 'Lead last name',
      },
      {
        crmField: 'Email',
        salesosField: 'email',
        aliases: ['email', 'Email Address', 'E-mail'],
        required: false,
        description: 'Lead email address',
      },
      {
        crmField: 'Phone Number',
        salesosField: 'phone',
        aliases: ['phone', 'Phone', 'phone_number', 'Telephone'],
        required: false,
        transform: 'parse_phone',
        description: 'Lead phone number',
      },
      {
        crmField: 'Mobile Phone Number',
        salesosField: 'mobile',
        aliases: ['mobilephone', 'Mobile', 'Cell Phone'],
        required: false,
        transform: 'parse_phone',
        description: 'Lead mobile phone',
      },
      {
        crmField: 'Company Name',
        salesosField: 'company',
        aliases: ['company', 'Company', 'Organization'],
        required: false,
        description: 'Company name',
      },
      {
        crmField: 'Job Title',
        salesosField: 'title',
        aliases: ['jobtitle', 'Title', 'Position'],
        required: false,
        description: 'Job title',
      },
      {
        crmField: 'Lead Status',
        salesosField: 'status',
        aliases: ['hs_lead_status', 'Status'],
        required: false,
        transform: 'map_status',
        description: 'Lead status',
      },
      {
        crmField: 'Original Source',
        salesosField: 'leadSource',
        aliases: ['hs_analytics_source', 'Lead Source', 'Source'],
        required: false,
        description: 'Original source',
      },
      {
        crmField: 'Industry',
        salesosField: 'industry',
        aliases: ['industry'],
        required: false,
        description: 'Industry',
      },
      {
        crmField: 'Number of Employees',
        salesosField: 'numberOfEmployees',
        aliases: ['numberofemployees', 'Employees'],
        required: false,
        description: 'Number of employees',
      },
      {
        crmField: 'Annual Revenue',
        salesosField: 'annualRevenue',
        aliases: ['annualrevenue', 'Revenue'],
        required: false,
        transform: 'parse_currency',
        description: 'Annual revenue',
      },
      {
        crmField: 'Website URL',
        salesosField: 'website',
        aliases: ['website', 'Website', 'URL'],
        required: false,
        description: 'Website URL',
      },
      {
        crmField: 'Street Address',
        salesosField: 'street',
        aliases: ['address', 'Address'],
        required: false,
        description: 'Street address',
      },
      {
        crmField: 'City',
        salesosField: 'city',
        aliases: ['city'],
        required: false,
        description: 'City',
      },
      {
        crmField: 'State/Region',
        salesosField: 'state',
        aliases: ['state', 'State', 'Region'],
        required: false,
        description: 'State or region',
      },
      {
        crmField: 'Postal Code',
        salesosField: 'postalCode',
        aliases: ['zip', 'Zip', 'ZIP Code'],
        required: false,
        description: 'Postal/ZIP code',
      },
      {
        crmField: 'Country/Region',
        salesosField: 'country',
        aliases: ['country', 'Country'],
        required: false,
        description: 'Country',
      },
    ],
    accounts: [
      {
        crmField: 'Company name',
        salesosField: 'name',
        aliases: ['name', 'Company Name', 'Name'],
        required: true,
        description: 'Company name',
      },
      {
        crmField: 'Company Domain Name',
        salesosField: 'domain',
        aliases: ['domain', 'Website Domain'],
        required: false,
        description: 'Company domain',
      },
      {
        crmField: 'Industry',
        salesosField: 'industry',
        aliases: ['industry'],
        required: false,
        description: 'Industry',
      },
      {
        crmField: 'Type',
        salesosField: 'type',
        aliases: ['type', 'Account Type'],
        required: false,
        description: 'Company type',
      },
      {
        crmField: 'Website URL',
        salesosField: 'website',
        aliases: ['website', 'Website'],
        required: false,
        description: 'Website URL',
      },
      {
        crmField: 'Phone Number',
        salesosField: 'phone',
        aliases: ['phone', 'Phone'],
        required: false,
        transform: 'parse_phone',
        description: 'Main phone number',
      },
      {
        crmField: 'Number of Employees',
        salesosField: 'numberOfEmployees',
        aliases: ['numberofemployees', 'Employees'],
        required: false,
        description: 'Number of employees',
      },
      {
        crmField: 'Annual Revenue',
        salesosField: 'annualRevenue',
        aliases: ['annualrevenue', 'Revenue'],
        required: false,
        transform: 'parse_currency',
        description: 'Annual revenue',
      },
      {
        crmField: 'Street Address',
        salesosField: 'billingStreet',
        aliases: ['address', 'Address'],
        required: false,
        description: 'Street address',
      },
      {
        crmField: 'City',
        salesosField: 'billingCity',
        aliases: ['city'],
        required: false,
        description: 'City',
      },
      {
        crmField: 'State/Region',
        salesosField: 'billingState',
        aliases: ['state', 'State'],
        required: false,
        description: 'State/region',
      },
      {
        crmField: 'Postal Code',
        salesosField: 'billingPostalCode',
        aliases: ['zip', 'Zip'],
        required: false,
        description: 'Postal/ZIP code',
      },
      {
        crmField: 'Country/Region',
        salesosField: 'billingCountry',
        aliases: ['country', 'Country'],
        required: false,
        description: 'Country',
      },
      {
        crmField: 'Description',
        salesosField: 'description',
        aliases: ['description', 'About'],
        required: false,
        description: 'Company description',
      },
    ],
    contacts: [
      {
        crmField: 'First Name',
        salesosField: 'firstName',
        aliases: ['firstname', 'First_Name'],
        required: true,
        description: 'Contact first name',
      },
      {
        crmField: 'Last Name',
        salesosField: 'lastName',
        aliases: ['lastname', 'Last_Name'],
        required: true,
        description: 'Contact last name',
      },
      {
        crmField: 'Email',
        salesosField: 'email',
        aliases: ['email', 'Email Address'],
        required: false,
        description: 'Contact email',
      },
      {
        crmField: 'Phone Number',
        salesosField: 'phone',
        aliases: ['phone', 'Phone'],
        required: false,
        transform: 'parse_phone',
        description: 'Contact phone',
      },
      {
        crmField: 'Mobile Phone Number',
        salesosField: 'mobile',
        aliases: ['mobilephone', 'Mobile'],
        required: false,
        transform: 'parse_phone',
        description: 'Contact mobile phone',
      },
      {
        crmField: 'Job Title',
        salesosField: 'title',
        aliases: ['jobtitle', 'Title'],
        required: false,
        description: 'Job title',
      },
      {
        crmField: 'Company name',
        salesosField: 'accountId',
        aliases: ['company', 'Company', 'Account Name'],
        required: false,
        transform: 'lookup_account',
        description: 'Associated company',
      },
      {
        crmField: 'Lead Status',
        salesosField: 'status',
        aliases: ['hs_lead_status', 'Status'],
        required: false,
        description: 'Contact status',
      },
      {
        crmField: 'Lifecycle Stage',
        salesosField: 'lifecycleStage',
        aliases: ['lifecyclestage', 'Stage'],
        required: false,
        description: 'Lifecycle stage',
      },
      {
        crmField: 'Street Address',
        salesosField: 'mailingStreet',
        aliases: ['address', 'Address'],
        required: false,
        description: 'Street address',
      },
      {
        crmField: 'City',
        salesosField: 'mailingCity',
        aliases: ['city'],
        required: false,
        description: 'City',
      },
      {
        crmField: 'State/Region',
        salesosField: 'mailingState',
        aliases: ['state', 'State'],
        required: false,
        description: 'State/region',
      },
      {
        crmField: 'Postal Code',
        salesosField: 'mailingPostalCode',
        aliases: ['zip', 'Zip'],
        required: false,
        description: 'Postal/ZIP code',
      },
      {
        crmField: 'Country/Region',
        salesosField: 'mailingCountry',
        aliases: ['country', 'Country'],
        required: false,
        description: 'Country',
      },
    ],
    opportunities: [
      {
        crmField: 'Deal Name',
        salesosField: 'name',
        aliases: ['dealname', 'Name', 'Opportunity Name'],
        required: true,
        description: 'Deal name',
      },
      {
        crmField: 'Company name',
        salesosField: 'accountId',
        aliases: ['associatedcompanyid', 'Company', 'Account'],
        required: false,
        transform: 'lookup_account',
        description: 'Associated company',
      },
      {
        crmField: 'Deal Stage',
        salesosField: 'stage',
        aliases: ['dealstage', 'Stage', 'Pipeline Stage'],
        required: true,
        transform: 'map_stage',
        description: 'Deal stage',
      },
      {
        crmField: 'Amount',
        salesosField: 'amount',
        aliases: ['amount', 'Deal Amount', 'Value'],
        required: false,
        transform: 'parse_currency',
        description: 'Deal amount',
      },
      {
        crmField: 'Close Date',
        salesosField: 'closeDate',
        aliases: ['closedate', 'Expected Close Date'],
        required: true,
        transform: 'parse_date',
        description: 'Expected close date',
      },
      {
        crmField: 'Deal Type',
        salesosField: 'type',
        aliases: ['dealtype', 'Type'],
        required: false,
        description: 'Deal type',
      },
      {
        crmField: 'Pipeline',
        salesosField: 'pipeline',
        aliases: ['pipeline', 'Deal Pipeline'],
        required: false,
        description: 'Pipeline name',
      },
      {
        crmField: 'Deal Description',
        salesosField: 'description',
        aliases: ['description', 'Notes'],
        required: false,
        description: 'Deal description',
      },
    ],
  },
  csvDelimiter: ',',
  hasHeader: true,
  specialHandling: {
    booleanFormat: 'true/false',
    currencySymbol: '$',
    dateFormat: ['YYYY-MM-DD', 'MM/DD/YYYY'],
  },
  notes: 'HubSpot exports use lowercase field names with spaces. Property names may vary if custom properties are used.',
};
