import { CRMTemplate } from './types';

/**
 * Monday.com CRM Template
 *
 * Field mappings for migrating from Monday.com to SalesOS.
 * Monday.com uses a flexible column-based system that may vary by workspace.
 */
export const mondayTemplate: CRMTemplate = {
  name: 'Monday.com',
  code: 'monday',
  exportFields: {
    leads: [
      {
        crmField: 'Name',
        salesosField: 'firstName',
        aliases: ['Lead Name', 'Contact Name', 'Person'],
        required: true,
        transform: 'split_name',
        description: 'Lead name (will be split)',
      },
      {
        crmField: 'Email',
        salesosField: 'email',
        aliases: ['Email Address', 'Contact Email'],
        required: false,
        description: 'Lead email',
      },
      {
        crmField: 'Phone',
        salesosField: 'phone',
        aliases: ['Phone Number', 'Contact Phone', 'Tel'],
        required: false,
        transform: 'parse_phone',
        description: 'Lead phone',
      },
      {
        crmField: 'Company',
        salesosField: 'company',
        aliases: ['Company Name', 'Organization', 'Account'],
        required: false,
        description: 'Company name',
      },
      {
        crmField: 'Title',
        salesosField: 'title',
        aliases: ['Job Title', 'Position', 'Role'],
        required: false,
        description: 'Job title',
      },
      {
        crmField: 'Status',
        salesosField: 'status',
        aliases: ['Lead Status', 'Stage'],
        required: false,
        transform: 'map_status',
        description: 'Lead status',
      },
      {
        crmField: 'Source',
        salesosField: 'leadSource',
        aliases: ['Lead Source', 'Origin'],
        required: false,
        description: 'Lead source',
      },
      {
        crmField: 'Value',
        salesosField: 'value',
        aliases: ['Deal Value', 'Amount', 'Potential Value'],
        required: false,
        transform: 'parse_currency',
        description: 'Potential value',
      },
      {
        crmField: 'Website',
        salesosField: 'website',
        aliases: ['Website URL', 'URL'],
        required: false,
        description: 'Website',
      },
      {
        crmField: 'Location',
        salesosField: 'city',
        aliases: ['City', 'Address'],
        required: false,
        description: 'Location/city',
      },
      {
        crmField: 'Country',
        salesosField: 'country',
        aliases: [],
        required: false,
        description: 'Country',
      },
    ],
    accounts: [
      {
        crmField: 'Name',
        salesosField: 'name',
        aliases: ['Account Name', 'Company Name', 'Organization'],
        required: true,
        description: 'Account name',
      },
      {
        crmField: 'Type',
        salesosField: 'type',
        aliases: ['Account Type', 'Category'],
        required: false,
        description: 'Account type',
      },
      {
        crmField: 'Industry',
        salesosField: 'industry',
        aliases: ['Sector'],
        required: false,
        description: 'Industry',
      },
      {
        crmField: 'Website',
        salesosField: 'website',
        aliases: ['Website URL', 'URL'],
        required: false,
        description: 'Website',
      },
      {
        crmField: 'Phone',
        salesosField: 'phone',
        aliases: ['Phone Number', 'Main Phone', 'Tel'],
        required: false,
        transform: 'parse_phone',
        description: 'Phone number',
      },
      {
        crmField: 'Employees',
        salesosField: 'numberOfEmployees',
        aliases: ['Number of Employees', 'Team Size', 'Staff Count'],
        required: false,
        description: 'Number of employees',
      },
      {
        crmField: 'Revenue',
        salesosField: 'annualRevenue',
        aliases: ['Annual Revenue', 'ARR'],
        required: false,
        transform: 'parse_currency',
        description: 'Annual revenue',
      },
      {
        crmField: 'Location',
        salesosField: 'billingStreet',
        aliases: ['Address', 'Street'],
        required: false,
        description: 'Address',
      },
      {
        crmField: 'City',
        salesosField: 'billingCity',
        aliases: [],
        required: false,
        description: 'City',
      },
      {
        crmField: 'State',
        salesosField: 'billingState',
        aliases: ['State/Province', 'Region'],
        required: false,
        description: 'State',
      },
      {
        crmField: 'ZIP',
        salesosField: 'billingPostalCode',
        aliases: ['Postal Code', 'Zip Code'],
        required: false,
        description: 'Postal code',
      },
      {
        crmField: 'Country',
        salesosField: 'billingCountry',
        aliases: [],
        required: false,
        description: 'Country',
      },
      {
        crmField: 'Notes',
        salesosField: 'description',
        aliases: ['Description', 'Comments'],
        required: false,
        description: 'Notes',
      },
    ],
    contacts: [
      {
        crmField: 'Name',
        salesosField: 'firstName',
        aliases: ['Contact Name', 'Person', 'Full Name'],
        required: true,
        transform: 'split_name',
        description: 'Contact name (will be split)',
      },
      {
        crmField: 'Email',
        salesosField: 'email',
        aliases: ['Email Address', 'Contact Email'],
        required: false,
        description: 'Contact email',
      },
      {
        crmField: 'Phone',
        salesosField: 'phone',
        aliases: ['Phone Number', 'Contact Phone', 'Tel'],
        required: false,
        transform: 'parse_phone',
        description: 'Contact phone',
      },
      {
        crmField: 'Mobile',
        salesosField: 'mobile',
        aliases: ['Mobile Phone', 'Cell', 'Cell Phone'],
        required: false,
        transform: 'parse_phone',
        description: 'Mobile phone',
      },
      {
        crmField: 'Title',
        salesosField: 'title',
        aliases: ['Job Title', 'Position', 'Role'],
        required: false,
        description: 'Job title',
      },
      {
        crmField: 'Company',
        salesosField: 'accountId',
        aliases: ['Account', 'Organization', 'Company Name'],
        required: false,
        transform: 'lookup_account',
        description: 'Associated company',
      },
      {
        crmField: 'Location',
        salesosField: 'mailingStreet',
        aliases: ['Address', 'Street'],
        required: false,
        description: 'Address',
      },
      {
        crmField: 'City',
        salesosField: 'mailingCity',
        aliases: [],
        required: false,
        description: 'City',
      },
      {
        crmField: 'Country',
        salesosField: 'mailingCountry',
        aliases: [],
        required: false,
        description: 'Country',
      },
    ],
    opportunities: [
      {
        crmField: 'Name',
        salesosField: 'name',
        aliases: ['Deal Name', 'Opportunity Name', 'Item'],
        required: true,
        description: 'Deal name',
      },
      {
        crmField: 'Account',
        salesosField: 'accountId',
        aliases: ['Company', 'Organization', 'Client'],
        required: false,
        transform: 'lookup_account',
        description: 'Associated account',
      },
      {
        crmField: 'Status',
        salesosField: 'stage',
        aliases: ['Stage', 'Deal Stage', 'Pipeline Stage'],
        required: true,
        transform: 'map_stage',
        description: 'Deal stage',
      },
      {
        crmField: 'Value',
        salesosField: 'amount',
        aliases: ['Amount', 'Deal Value', 'Numbers'],
        required: false,
        transform: 'parse_currency',
        description: 'Deal value',
      },
      {
        crmField: 'Close Date',
        salesosField: 'closeDate',
        aliases: ['Expected Close', 'Target Date', 'Due Date', 'Date'],
        required: true,
        transform: 'parse_date',
        description: 'Expected close date',
      },
      {
        crmField: 'Probability',
        salesosField: 'probability',
        aliases: ['Win Probability', 'Confidence', 'Likelihood'],
        required: false,
        description: 'Win probability',
      },
      {
        crmField: 'Type',
        salesosField: 'type',
        aliases: ['Deal Type', 'Category'],
        required: false,
        description: 'Deal type',
      },
      {
        crmField: 'Notes',
        salesosField: 'description',
        aliases: ['Description', 'Comments', 'Updates'],
        required: false,
        description: 'Notes',
      },
    ],
  },
  csvDelimiter: ',',
  hasHeader: true,
  specialHandling: {
    booleanFormat: 'Yes/No',
    currencySymbol: '$',
    dateFormat: ['YYYY-MM-DD', 'MM/DD/YYYY', 'DD/MM/YYYY'],
  },
  notes: 'Monday.com boards are highly customizable. Field names may vary significantly. This template covers common column names.',
};
