import { CRMTemplate } from './types';

/**
 * Pipedrive CRM Template
 *
 * Field mappings for migrating from Pipedrive to SalesOS.
 * Pipedrive has a simpler field structure focused on sales.
 */
export const pipedriveTemplate: CRMTemplate = {
  name: 'Pipedrive',
  code: 'pipedrive',
  exportFields: {
    leads: [
      {
        crmField: 'Title',
        salesosField: 'firstName',
        aliases: ['Person name', 'Name', 'Lead Title'],
        required: true,
        transform: 'split_name',
        description: 'Lead name (will be split into first/last)',
      },
      {
        crmField: 'Email',
        salesosField: 'email',
        aliases: ['Email address', 'Primary email'],
        required: false,
        description: 'Lead email',
      },
      {
        crmField: 'Phone',
        salesosField: 'phone',
        aliases: ['Phone number', 'Primary phone'],
        required: false,
        transform: 'parse_phone',
        description: 'Lead phone',
      },
      {
        crmField: 'Organization',
        salesosField: 'company',
        aliases: ['Organization name', 'Company'],
        required: false,
        description: 'Company name',
      },
      {
        crmField: 'Label',
        salesosField: 'status',
        aliases: ['Lead label', 'Status'],
        required: false,
        description: 'Lead label/status',
      },
      {
        crmField: 'Value',
        salesosField: 'value',
        aliases: ['Lead value', 'Expected value'],
        required: false,
        transform: 'parse_currency',
        description: 'Potential value',
      },
      {
        crmField: 'Source',
        salesosField: 'leadSource',
        aliases: ['Lead source'],
        required: false,
        description: 'Lead source',
      },
    ],
    accounts: [
      {
        crmField: 'Name',
        salesosField: 'name',
        aliases: ['Organization name', 'Company name'],
        required: true,
        description: 'Organization name',
      },
      {
        crmField: 'Address',
        salesosField: 'billingStreet',
        aliases: ['Street address', 'Address line 1'],
        required: false,
        description: 'Street address',
      },
      {
        crmField: 'City',
        salesosField: 'billingCity',
        aliases: [],
        required: false,
        description: 'City',
      },
      {
        crmField: 'State',
        salesosField: 'billingState',
        aliases: ['State/Province'],
        required: false,
        description: 'State/province',
      },
      {
        crmField: 'Postal code',
        salesosField: 'billingPostalCode',
        aliases: ['ZIP code', 'Postcode'],
        required: false,
        description: 'Postal/ZIP code',
      },
      {
        crmField: 'Country',
        salesosField: 'billingCountry',
        aliases: [],
        required: false,
        description: 'Country',
      },
      {
        crmField: 'Website',
        salesosField: 'website',
        aliases: ['Website URL', 'URL'],
        required: false,
        description: 'Website',
      },
      {
        crmField: 'Phone',
        salesosField: 'phone',
        aliases: ['Phone number', 'Primary phone'],
        required: false,
        transform: 'parse_phone',
        description: 'Phone number',
      },
      {
        crmField: 'People count',
        salesosField: 'numberOfEmployees',
        aliases: ['Number of employees', 'Employees'],
        required: false,
        description: 'Number of people/employees',
      },
    ],
    contacts: [
      {
        crmField: 'Name',
        salesosField: 'firstName',
        aliases: ['Person name', 'Contact name'],
        required: true,
        transform: 'split_name',
        description: 'Contact name (will be split)',
      },
      {
        crmField: 'Email',
        salesosField: 'email',
        aliases: ['Email address', 'Primary email'],
        required: false,
        description: 'Contact email',
      },
      {
        crmField: 'Phone',
        salesosField: 'phone',
        aliases: ['Phone number', 'Primary phone'],
        required: false,
        transform: 'parse_phone',
        description: 'Contact phone',
      },
      {
        crmField: 'Organization',
        salesosField: 'accountId',
        aliases: ['Organization name', 'Company', 'Account'],
        required: false,
        transform: 'lookup_account',
        description: 'Associated organization',
      },
      {
        crmField: 'Job title',
        salesosField: 'title',
        aliases: ['Title', 'Position'],
        required: false,
        description: 'Job title',
      },
    ],
    opportunities: [
      {
        crmField: 'Title',
        salesosField: 'name',
        aliases: ['Deal title', 'Deal name', 'Name'],
        required: true,
        description: 'Deal title',
      },
      {
        crmField: 'Organization',
        salesosField: 'accountId',
        aliases: ['Organization name', 'Company', 'Account'],
        required: false,
        transform: 'lookup_account',
        description: 'Associated organization',
      },
      {
        crmField: 'Stage',
        salesosField: 'stage',
        aliases: ['Deal stage', 'Pipeline stage'],
        required: true,
        transform: 'map_stage',
        description: 'Deal stage',
      },
      {
        crmField: 'Value',
        salesosField: 'amount',
        aliases: ['Deal value', 'Amount'],
        required: false,
        transform: 'parse_currency',
        description: 'Deal value',
      },
      {
        crmField: 'Expected close date',
        salesosField: 'closeDate',
        aliases: ['Close date', 'Expected close', 'Close Date'],
        required: true,
        transform: 'parse_date',
        description: 'Expected close date',
      },
      {
        crmField: 'Status',
        salesosField: 'status',
        aliases: ['Deal status'],
        required: false,
        description: 'Deal status (Open/Won/Lost)',
      },
      {
        crmField: 'Probability',
        salesosField: 'probability',
        aliases: ['Win probability', 'Deal probability'],
        required: false,
        description: 'Win probability',
      },
      {
        crmField: 'Pipeline',
        salesosField: 'pipeline',
        aliases: ['Pipeline name'],
        required: false,
        description: 'Pipeline',
      },
    ],
  },
  csvDelimiter: ',',
  hasHeader: true,
  specialHandling: {
    booleanFormat: '1/0',
    currencySymbol: '$',
    dateFormat: ['YYYY-MM-DD', 'DD.MM.YYYY'],
  },
  notes: 'Pipedrive exports combine first and last names into a single "Name" field. Use split_name transform to separate them.',
};
