import { CRMTemplate } from './types';

/**
 * Salesforce CRM Template
 *
 * Field mappings for migrating from Salesforce to SalesOS.
 * Based on standard Salesforce objects and field names.
 */
export const salesforceTemplate: CRMTemplate = {
  name: 'Salesforce',
  code: 'salesforce',
  exportFields: {
    leads: [
      {
        crmField: 'FirstName',
        salesosField: 'firstName',
        aliases: ['First Name', 'First_Name', 'fname'],
        required: true,
        description: 'Lead first name',
      },
      {
        crmField: 'LastName',
        salesosField: 'lastName',
        aliases: ['Last Name', 'Last_Name', 'lname', 'Surname'],
        required: true,
        description: 'Lead last name',
      },
      {
        crmField: 'Email',
        salesosField: 'email',
        aliases: ['Email Address', 'Email_Address', 'E-mail', 'EmailAddress'],
        required: false,
        description: 'Lead email address',
      },
      {
        crmField: 'Phone',
        salesosField: 'phone',
        aliases: ['Phone Number', 'Phone_Number', 'PhoneNumber', 'Telephone'],
        required: false,
        transform: 'parse_phone',
        description: 'Lead phone number',
      },
      {
        crmField: 'MobilePhone',
        salesosField: 'mobile',
        aliases: ['Mobile', 'Mobile Phone', 'Mobile_Phone', 'Cell', 'CellPhone'],
        required: false,
        transform: 'parse_phone',
        description: 'Lead mobile phone',
      },
      {
        crmField: 'Company',
        salesosField: 'company',
        aliases: ['Company Name', 'Company_Name', 'Organization'],
        required: false,
        description: 'Company name',
      },
      {
        crmField: 'Title',
        salesosField: 'title',
        aliases: ['Job Title', 'Job_Title', 'Position', 'JobTitle'],
        required: false,
        description: 'Job title',
      },
      {
        crmField: 'LeadSource',
        salesosField: 'leadSource',
        aliases: ['Lead Source', 'Lead_Source', 'Source'],
        required: false,
        description: 'Lead source',
      },
      {
        crmField: 'Status',
        salesosField: 'status',
        aliases: ['Lead Status', 'Lead_Status', 'LeadStatus'],
        required: false,
        transform: 'map_status',
        description: 'Lead status',
      },
      {
        crmField: 'Rating',
        salesosField: 'rating',
        aliases: ['Lead Rating', 'Lead_Rating'],
        required: false,
        description: 'Lead rating (Hot/Warm/Cold)',
      },
      {
        crmField: 'Industry',
        salesosField: 'industry',
        aliases: [],
        required: false,
        description: 'Industry',
      },
      {
        crmField: 'NumberOfEmployees',
        salesosField: 'numberOfEmployees',
        aliases: ['Employees', 'Employee Count', 'Number_Of_Employees'],
        required: false,
        description: 'Number of employees',
      },
      {
        crmField: 'AnnualRevenue',
        salesosField: 'annualRevenue',
        aliases: ['Revenue', 'Annual Revenue', 'Annual_Revenue'],
        required: false,
        transform: 'parse_currency',
        description: 'Annual revenue',
      },
      {
        crmField: 'Website',
        salesosField: 'website',
        aliases: ['Web Site', 'Web_Site', 'URL'],
        required: false,
        description: 'Website URL',
      },
      {
        crmField: 'Street',
        salesosField: 'street',
        aliases: ['Address', 'Street Address', 'Address Line 1'],
        required: false,
        description: 'Street address',
      },
      {
        crmField: 'City',
        salesosField: 'city',
        aliases: [],
        required: false,
        description: 'City',
      },
      {
        crmField: 'State',
        salesosField: 'state',
        aliases: ['State/Province', 'Province'],
        required: false,
        description: 'State or province',
      },
      {
        crmField: 'PostalCode',
        salesosField: 'postalCode',
        aliases: ['Postal Code', 'Postal_Code', 'Zip', 'Zip Code', 'ZipCode'],
        required: false,
        description: 'Postal/ZIP code',
      },
      {
        crmField: 'Country',
        salesosField: 'country',
        aliases: [],
        required: false,
        description: 'Country',
      },
      {
        crmField: 'Description',
        salesosField: 'description',
        aliases: ['Notes', 'Comments'],
        required: false,
        description: 'Description or notes',
      },
    ],
    accounts: [
      {
        crmField: 'Name',
        salesosField: 'name',
        aliases: ['Account Name', 'Account_Name', 'AccountName', 'Company Name'],
        required: true,
        description: 'Account name',
      },
      {
        crmField: 'Type',
        salesosField: 'type',
        aliases: ['Account Type', 'Account_Type', 'AccountType'],
        required: false,
        description: 'Account type (Customer, Prospect, Partner, etc.)',
      },
      {
        crmField: 'Industry',
        salesosField: 'industry',
        aliases: [],
        required: false,
        description: 'Industry',
      },
      {
        crmField: 'Website',
        salesosField: 'website',
        aliases: ['Web Site', 'Web_Site', 'URL'],
        required: false,
        description: 'Website URL',
      },
      {
        crmField: 'Phone',
        salesosField: 'phone',
        aliases: ['Main Phone', 'Phone Number', 'Telephone'],
        required: false,
        transform: 'parse_phone',
        description: 'Main phone number',
      },
      {
        crmField: 'NumberOfEmployees',
        salesosField: 'numberOfEmployees',
        aliases: ['Employees', 'Employee Count', 'Number_Of_Employees'],
        required: false,
        description: 'Number of employees',
      },
      {
        crmField: 'AnnualRevenue',
        salesosField: 'annualRevenue',
        aliases: ['Revenue', 'Annual Revenue', 'Annual_Revenue'],
        required: false,
        transform: 'parse_currency',
        description: 'Annual revenue',
      },
      {
        crmField: 'BillingStreet',
        salesosField: 'billingStreet',
        aliases: ['Billing Address', 'Billing_Address', 'Street'],
        required: false,
        description: 'Billing street address',
      },
      {
        crmField: 'BillingCity',
        salesosField: 'billingCity',
        aliases: ['Billing City', 'Billing_City', 'City'],
        required: false,
        description: 'Billing city',
      },
      {
        crmField: 'BillingState',
        salesosField: 'billingState',
        aliases: ['Billing State', 'Billing_State', 'State'],
        required: false,
        description: 'Billing state/province',
      },
      {
        crmField: 'BillingPostalCode',
        salesosField: 'billingPostalCode',
        aliases: ['Billing Postal Code', 'Billing_Postal_Code', 'Billing Zip', 'PostalCode'],
        required: false,
        description: 'Billing postal/ZIP code',
      },
      {
        crmField: 'BillingCountry',
        salesosField: 'billingCountry',
        aliases: ['Billing Country', 'Billing_Country', 'Country'],
        required: false,
        description: 'Billing country',
      },
      {
        crmField: 'ShippingStreet',
        salesosField: 'shippingStreet',
        aliases: ['Shipping Address', 'Shipping_Address'],
        required: false,
        description: 'Shipping street address',
      },
      {
        crmField: 'ShippingCity',
        salesosField: 'shippingCity',
        aliases: ['Shipping City', 'Shipping_City'],
        required: false,
        description: 'Shipping city',
      },
      {
        crmField: 'ShippingState',
        salesosField: 'shippingState',
        aliases: ['Shipping State', 'Shipping_State'],
        required: false,
        description: 'Shipping state/province',
      },
      {
        crmField: 'ShippingPostalCode',
        salesosField: 'shippingPostalCode',
        aliases: ['Shipping Postal Code', 'Shipping_Postal_Code', 'Shipping Zip'],
        required: false,
        description: 'Shipping postal/ZIP code',
      },
      {
        crmField: 'ShippingCountry',
        salesosField: 'shippingCountry',
        aliases: ['Shipping Country', 'Shipping_Country'],
        required: false,
        description: 'Shipping country',
      },
      {
        crmField: 'Description',
        salesosField: 'description',
        aliases: ['Notes', 'Comments'],
        required: false,
        description: 'Description or notes',
      },
    ],
    contacts: [
      {
        crmField: 'FirstName',
        salesosField: 'firstName',
        aliases: ['First Name', 'First_Name', 'fname'],
        required: true,
        description: 'Contact first name',
      },
      {
        crmField: 'LastName',
        salesosField: 'lastName',
        aliases: ['Last Name', 'Last_Name', 'lname', 'Surname'],
        required: true,
        description: 'Contact last name',
      },
      {
        crmField: 'Email',
        salesosField: 'email',
        aliases: ['Email Address', 'Email_Address', 'E-mail', 'EmailAddress'],
        required: false,
        description: 'Contact email address',
      },
      {
        crmField: 'Phone',
        salesosField: 'phone',
        aliases: ['Phone Number', 'Phone_Number', 'PhoneNumber', 'Telephone'],
        required: false,
        transform: 'parse_phone',
        description: 'Contact phone number',
      },
      {
        crmField: 'MobilePhone',
        salesosField: 'mobile',
        aliases: ['Mobile', 'Mobile Phone', 'Mobile_Phone', 'Cell', 'CellPhone'],
        required: false,
        transform: 'parse_phone',
        description: 'Contact mobile phone',
      },
      {
        crmField: 'Title',
        salesosField: 'title',
        aliases: ['Job Title', 'Job_Title', 'Position', 'JobTitle'],
        required: false,
        description: 'Job title',
      },
      {
        crmField: 'AccountId',
        salesosField: 'accountId',
        aliases: ['Account ID', 'Account_ID', 'Account Name', 'Account_Name', 'Company'],
        required: false,
        transform: 'lookup_account',
        description: 'Associated account (ID or name)',
      },
      {
        crmField: 'Department',
        salesosField: 'department',
        aliases: [],
        required: false,
        description: 'Department',
      },
      {
        crmField: 'LeadSource',
        salesosField: 'leadSource',
        aliases: ['Lead Source', 'Lead_Source', 'Source'],
        required: false,
        description: 'Lead source',
      },
      {
        crmField: 'MailingStreet',
        salesosField: 'mailingStreet',
        aliases: ['Mailing Address', 'Mailing_Address', 'Street', 'Address'],
        required: false,
        description: 'Mailing street address',
      },
      {
        crmField: 'MailingCity',
        salesosField: 'mailingCity',
        aliases: ['Mailing City', 'Mailing_City', 'City'],
        required: false,
        description: 'Mailing city',
      },
      {
        crmField: 'MailingState',
        salesosField: 'mailingState',
        aliases: ['Mailing State', 'Mailing_State', 'State'],
        required: false,
        description: 'Mailing state/province',
      },
      {
        crmField: 'MailingPostalCode',
        salesosField: 'mailingPostalCode',
        aliases: ['Mailing Postal Code', 'Mailing_Postal_Code', 'Mailing Zip', 'PostalCode'],
        required: false,
        description: 'Mailing postal/ZIP code',
      },
      {
        crmField: 'MailingCountry',
        salesosField: 'mailingCountry',
        aliases: ['Mailing Country', 'Mailing_Country', 'Country'],
        required: false,
        description: 'Mailing country',
      },
      {
        crmField: 'Description',
        salesosField: 'description',
        aliases: ['Notes', 'Comments'],
        required: false,
        description: 'Description or notes',
      },
    ],
    opportunities: [
      {
        crmField: 'Name',
        salesosField: 'name',
        aliases: ['Opportunity Name', 'Opportunity_Name', 'OpportunityName', 'Deal Name'],
        required: true,
        description: 'Opportunity name',
      },
      {
        crmField: 'AccountId',
        salesosField: 'accountId',
        aliases: ['Account ID', 'Account_ID', 'Account Name', 'Account_Name', 'Company'],
        required: false,
        transform: 'lookup_account',
        description: 'Associated account (ID or name)',
      },
      {
        crmField: 'StageName',
        salesosField: 'stage',
        aliases: ['Stage', 'Stage Name', 'Stage_Name', 'Pipeline Stage'],
        required: true,
        transform: 'map_stage',
        description: 'Opportunity stage',
      },
      {
        crmField: 'Amount',
        salesosField: 'amount',
        aliases: ['Opportunity Amount', 'Opportunity_Amount', 'Deal Value', 'Value'],
        required: false,
        transform: 'parse_currency',
        description: 'Opportunity amount',
      },
      {
        crmField: 'CloseDate',
        salesosField: 'closeDate',
        aliases: ['Close Date', 'Close_Date', 'Expected Close', 'Expected_Close_Date'],
        required: true,
        transform: 'parse_date',
        description: 'Expected close date',
      },
      {
        crmField: 'Probability',
        salesosField: 'probability',
        aliases: ['Win Probability', 'Win_Probability', 'Confidence'],
        required: false,
        description: 'Win probability (0-100)',
      },
      {
        crmField: 'Type',
        salesosField: 'type',
        aliases: ['Opportunity Type', 'Opportunity_Type', 'Deal Type'],
        required: false,
        description: 'Opportunity type (New Business, Renewal, Upsell, etc.)',
      },
      {
        crmField: 'LeadSource',
        salesosField: 'leadSource',
        aliases: ['Lead Source', 'Lead_Source', 'Source'],
        required: false,
        description: 'Lead source',
      },
      {
        crmField: 'NextStep',
        salesosField: 'nextStep',
        aliases: ['Next Step', 'Next_Step', 'Next Action'],
        required: false,
        description: 'Next step in sales process',
      },
      {
        crmField: 'Description',
        salesosField: 'description',
        aliases: ['Notes', 'Comments'],
        required: false,
        description: 'Description or notes',
      },
      {
        crmField: 'IsClosed',
        salesosField: 'isClosed',
        aliases: ['Is Closed', 'Is_Closed', 'Closed'],
        required: false,
        transform: 'parse_boolean',
        description: 'Whether opportunity is closed',
      },
      {
        crmField: 'IsWon',
        salesosField: 'isWon',
        aliases: ['Is Won', 'Is_Won', 'Won'],
        required: false,
        transform: 'parse_boolean',
        description: 'Whether opportunity was won',
      },
      {
        crmField: 'ForecastCategory',
        salesosField: 'forecastCategory',
        aliases: ['Forecast Category', 'Forecast_Category', 'Forecast'],
        required: false,
        description: 'Forecast category',
      },
    ],
  },
  csvDelimiter: ',',
  hasHeader: true,
  specialHandling: {
    booleanFormat: 'true/false',
    currencySymbol: '$',
    dateFormat: ['MM/DD/YYYY', 'YYYY-MM-DD', 'M/D/YYYY'],
  },
  notes: 'Salesforce exports typically use comma-separated values with quoted strings. Date format varies by locale settings.',
};
