import { CRMTemplate } from './types';

/**
 * Zoho CRM Template
 *
 * Field mappings for migrating from Zoho CRM to SalesOS.
 * Zoho uses similar conventions to Salesforce with some variations.
 */
export const zohoTemplate: CRMTemplate = {
  name: 'Zoho CRM',
  code: 'zoho',
  exportFields: {
    leads: [
      {
        crmField: 'First Name',
        salesosField: 'firstName',
        aliases: ['FirstName', 'First_Name'],
        required: true,
        description: 'Lead first name',
      },
      {
        crmField: 'Last Name',
        salesosField: 'lastName',
        aliases: ['LastName', 'Last_Name'],
        required: true,
        description: 'Lead last name',
      },
      {
        crmField: 'Email',
        salesosField: 'email',
        aliases: ['Email Address', 'Primary Email'],
        required: false,
        description: 'Lead email',
      },
      {
        crmField: 'Phone',
        salesosField: 'phone',
        aliases: ['Phone Number', 'Primary Phone'],
        required: false,
        transform: 'parse_phone',
        description: 'Lead phone',
      },
      {
        crmField: 'Mobile',
        salesosField: 'mobile',
        aliases: ['Mobile Number', 'Cell Phone'],
        required: false,
        transform: 'parse_phone',
        description: 'Lead mobile',
      },
      {
        crmField: 'Company',
        salesosField: 'company',
        aliases: ['Company Name', 'Organization'],
        required: false,
        description: 'Company name',
      },
      {
        crmField: 'Title',
        salesosField: 'title',
        aliases: ['Job Title', 'Designation'],
        required: false,
        description: 'Job title',
      },
      {
        crmField: 'Lead Status',
        salesosField: 'status',
        aliases: ['Status'],
        required: false,
        transform: 'map_status',
        description: 'Lead status',
      },
      {
        crmField: 'Lead Source',
        salesosField: 'leadSource',
        aliases: ['Source'],
        required: false,
        description: 'Lead source',
      },
      {
        crmField: 'Rating',
        salesosField: 'rating',
        aliases: ['Lead Rating'],
        required: false,
        description: 'Lead rating',
      },
      {
        crmField: 'Industry',
        salesosField: 'industry',
        aliases: [],
        required: false,
        description: 'Industry',
      },
      {
        crmField: 'No of Employees',
        salesosField: 'numberOfEmployees',
        aliases: ['Number of Employees', 'Employees'],
        required: false,
        description: 'Number of employees',
      },
      {
        crmField: 'Annual Revenue',
        salesosField: 'annualRevenue',
        aliases: ['Revenue'],
        required: false,
        transform: 'parse_currency',
        description: 'Annual revenue',
      },
      {
        crmField: 'Website',
        salesosField: 'website',
        aliases: ['Website URL'],
        required: false,
        description: 'Website',
      },
      {
        crmField: 'Street',
        salesosField: 'street',
        aliases: ['Address', 'Street Address'],
        required: false,
        description: 'Street address',
      },
      {
        crmField: 'City',
        salesosField: 'city',
        aliases: [],
        required: false,
        description: 'City',
      },
      {
        crmField: 'State',
        salesosField: 'state',
        aliases: ['State/Province'],
        required: false,
        description: 'State',
      },
      {
        crmField: 'Zip Code',
        salesosField: 'postalCode',
        aliases: ['Postal Code', 'ZIP'],
        required: false,
        description: 'Postal/ZIP code',
      },
      {
        crmField: 'Country',
        salesosField: 'country',
        aliases: [],
        required: false,
        description: 'Country',
      },
      {
        crmField: 'Description',
        salesosField: 'description',
        aliases: ['Notes', 'Comments'],
        required: false,
        description: 'Description',
      },
    ],
    accounts: [
      {
        crmField: 'Account Name',
        salesosField: 'name',
        aliases: ['Name', 'Company Name'],
        required: true,
        description: 'Account name',
      },
      {
        crmField: 'Account Type',
        salesosField: 'type',
        aliases: ['Type'],
        required: false,
        description: 'Account type',
      },
      {
        crmField: 'Industry',
        salesosField: 'industry',
        aliases: [],
        required: false,
        description: 'Industry',
      },
      {
        crmField: 'Website',
        salesosField: 'website',
        aliases: ['Website URL'],
        required: false,
        description: 'Website',
      },
      {
        crmField: 'Phone',
        salesosField: 'phone',
        aliases: ['Phone Number', 'Main Phone'],
        required: false,
        transform: 'parse_phone',
        description: 'Phone number',
      },
      {
        crmField: 'Employees',
        salesosField: 'numberOfEmployees',
        aliases: ['No of Employees', 'Number of Employees'],
        required: false,
        description: 'Number of employees',
      },
      {
        crmField: 'Annual Revenue',
        salesosField: 'annualRevenue',
        aliases: ['Revenue'],
        required: false,
        transform: 'parse_currency',
        description: 'Annual revenue',
      },
      {
        crmField: 'Billing Street',
        salesosField: 'billingStreet',
        aliases: ['Billing Address'],
        required: false,
        description: 'Billing street',
      },
      {
        crmField: 'Billing City',
        salesosField: 'billingCity',
        aliases: [],
        required: false,
        description: 'Billing city',
      },
      {
        crmField: 'Billing State',
        salesosField: 'billingState',
        aliases: [],
        required: false,
        description: 'Billing state',
      },
      {
        crmField: 'Billing Code',
        salesosField: 'billingPostalCode',
        aliases: ['Billing Zip', 'Billing Postal Code'],
        required: false,
        description: 'Billing postal code',
      },
      {
        crmField: 'Billing Country',
        salesosField: 'billingCountry',
        aliases: [],
        required: false,
        description: 'Billing country',
      },
      {
        crmField: 'Shipping Street',
        salesosField: 'shippingStreet',
        aliases: ['Shipping Address'],
        required: false,
        description: 'Shipping street',
      },
      {
        crmField: 'Shipping City',
        salesosField: 'shippingCity',
        aliases: [],
        required: false,
        description: 'Shipping city',
      },
      {
        crmField: 'Shipping State',
        salesosField: 'shippingState',
        aliases: [],
        required: false,
        description: 'Shipping state',
      },
      {
        crmField: 'Shipping Code',
        salesosField: 'shippingPostalCode',
        aliases: ['Shipping Zip', 'Shipping Postal Code'],
        required: false,
        description: 'Shipping postal code',
      },
      {
        crmField: 'Shipping Country',
        salesosField: 'shippingCountry',
        aliases: [],
        required: false,
        description: 'Shipping country',
      },
      {
        crmField: 'Description',
        salesosField: 'description',
        aliases: ['Notes'],
        required: false,
        description: 'Description',
      },
    ],
    contacts: [
      {
        crmField: 'First Name',
        salesosField: 'firstName',
        aliases: ['FirstName'],
        required: true,
        description: 'Contact first name',
      },
      {
        crmField: 'Last Name',
        salesosField: 'lastName',
        aliases: ['LastName'],
        required: true,
        description: 'Contact last name',
      },
      {
        crmField: 'Email',
        salesosField: 'email',
        aliases: ['Email Address'],
        required: false,
        description: 'Contact email',
      },
      {
        crmField: 'Phone',
        salesosField: 'phone',
        aliases: ['Phone Number'],
        required: false,
        transform: 'parse_phone',
        description: 'Contact phone',
      },
      {
        crmField: 'Mobile',
        salesosField: 'mobile',
        aliases: ['Mobile Number'],
        required: false,
        transform: 'parse_phone',
        description: 'Contact mobile',
      },
      {
        crmField: 'Title',
        salesosField: 'title',
        aliases: ['Job Title'],
        required: false,
        description: 'Job title',
      },
      {
        crmField: 'Account Name',
        salesosField: 'accountId',
        aliases: ['Account', 'Company', 'Organization'],
        required: false,
        transform: 'lookup_account',
        description: 'Associated account',
      },
      {
        crmField: 'Department',
        salesosField: 'department',
        aliases: [],
        required: false,
        description: 'Department',
      },
      {
        crmField: 'Lead Source',
        salesosField: 'leadSource',
        aliases: ['Source'],
        required: false,
        description: 'Lead source',
      },
      {
        crmField: 'Mailing Street',
        salesosField: 'mailingStreet',
        aliases: ['Mailing Address'],
        required: false,
        description: 'Mailing street',
      },
      {
        crmField: 'Mailing City',
        salesosField: 'mailingCity',
        aliases: [],
        required: false,
        description: 'Mailing city',
      },
      {
        crmField: 'Mailing State',
        salesosField: 'mailingState',
        aliases: [],
        required: false,
        description: 'Mailing state',
      },
      {
        crmField: 'Mailing Zip',
        salesosField: 'mailingPostalCode',
        aliases: ['Mailing Postal Code', 'Mailing Code'],
        required: false,
        description: 'Mailing postal code',
      },
      {
        crmField: 'Mailing Country',
        salesosField: 'mailingCountry',
        aliases: [],
        required: false,
        description: 'Mailing country',
      },
      {
        crmField: 'Description',
        salesosField: 'description',
        aliases: ['Notes'],
        required: false,
        description: 'Description',
      },
    ],
    opportunities: [
      {
        crmField: 'Deal Name',
        salesosField: 'name',
        aliases: ['Opportunity Name', 'Name'],
        required: true,
        description: 'Deal name',
      },
      {
        crmField: 'Account Name',
        salesosField: 'accountId',
        aliases: ['Account', 'Company'],
        required: false,
        transform: 'lookup_account',
        description: 'Associated account',
      },
      {
        crmField: 'Stage',
        salesosField: 'stage',
        aliases: ['Deal Stage', 'Sales Stage'],
        required: true,
        transform: 'map_stage',
        description: 'Deal stage',
      },
      {
        crmField: 'Amount',
        salesosField: 'amount',
        aliases: ['Deal Amount', 'Value'],
        required: false,
        transform: 'parse_currency',
        description: 'Deal amount',
      },
      {
        crmField: 'Closing Date',
        salesosField: 'closeDate',
        aliases: ['Close Date', 'Expected Close Date'],
        required: true,
        transform: 'parse_date',
        description: 'Closing date',
      },
      {
        crmField: 'Probability',
        salesosField: 'probability',
        aliases: ['Win Probability'],
        required: false,
        description: 'Win probability',
      },
      {
        crmField: 'Type',
        salesosField: 'type',
        aliases: ['Deal Type', 'Opportunity Type'],
        required: false,
        description: 'Deal type',
      },
      {
        crmField: 'Lead Source',
        salesosField: 'leadSource',
        aliases: ['Source'],
        required: false,
        description: 'Lead source',
      },
      {
        crmField: 'Next Step',
        salesosField: 'nextStep',
        aliases: ['Next Action'],
        required: false,
        description: 'Next step',
      },
      {
        crmField: 'Description',
        salesosField: 'description',
        aliases: ['Notes'],
        required: false,
        description: 'Description',
      },
    ],
  },
  csvDelimiter: ',',
  hasHeader: true,
  specialHandling: {
    booleanFormat: 'true/false',
    currencySymbol: '$',
    dateFormat: ['MM/DD/YYYY', 'DD-MM-YYYY', 'YYYY-MM-DD'],
  },
  notes: 'Zoho CRM exports are similar to Salesforce but with some field name variations. Date format can vary by locale.',
};
